---
- name: Validate SSH configuration
  ansible.builtin.command: /usr/sbin/sshd -t
  changed_when: false
  listen: Reload ssh

- name: Reload SSH configuration
  ansible.builtin.systemd:
    name: ssh
    state: reloaded
  listen: Reload ssh
