apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblioapibonus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: biblioapibonus
  template:
    metadata:
      labels:
        app: biblioapibonus
        tier: frontend
    spec:
      containers:
        - name : bibliotest
          image: "seb54000/tpkube-biblioapi:working"  # tags : working, broken , working-v2
          command: ["/bin/bash"]
          args: ["docker-entrypoint.sh"]
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata :
  name : biblioapibonusloadbalancer
spec:
  type: LoadBalancer
  selector:
    "tier": "frontend"
  ports:
    - port: 80
      name: hapijsport
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
  name: bgd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  # strategy: 
  #   type: Recreate
  ####
  # strategy: 
  #   type: RollingUpdate    
  ####
  # strategy:
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 0  
  ###
  # strategy: 
  #   type: RollingUpdate
  #   rollingUpdate:
  #     maxSurge: 0
  #     maxUnavailable: 20%
  ###
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgd
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: bgd
        env:
        - name: COLOR
          value: "green"
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bgd
  name: bgd
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: bgd
---