
- name: Get Terraform variables
  hosts: localhost, group_vms_student, group_access
  become: false
  become_user: florian
  run_once: true
  tasks:
    - name: Export terraform variables
      ansible.builtin.shell: terraform output -json
      args:
        chdir: terraform-infra
      register: terraform_output

    - name: Read Terraform outputs JSON file
      set_fact:
        tf_vars: "{{ terraform_output.stdout | from_json }}"
  tags: always
    
    # - name: Afficher les variables Terraform
    #   debug:
    #     msg: "La valeur de tf_vars est {{ tf_vars }}"
     
- name: Common role for all vms
  hosts: all
  become: true
  roles:
   - common
  tags:
    - common

- name: Call access_docs role
  hosts: group_access
  become: true
  roles:
   - access_docs
  tags:
    - access_docs

- name: Call vms_student role
  hosts: group_vms_student 
  become: true
  roles:
   - vms_student
  tags:
    - vms_student