- name: Remove existing tpcs-iac directory if present # Not really idempotent but git clone fails if the directory is not empty
  ansible.builtin.file:
    path: /home/{{ ansible_hostname }}/tpcs-iac
    state: absent

- name: git clone tpiac
  become_user: "{{ ansible_hostname }}"
  ansible.builtin.git:
    dest: /home/{{ ansible_hostname }}/tpcs-iac
    repo: https://github.com/seb54000/tpcs-iac.git

- name: Template and Copy student template files (either for tpiac or tpkube)
  ansible.builtin.template:
    src: "tpiac/.env.j2"
    dest: "/home/{{ ansible_hostname }}/tpcs-iac/.env"
    owner: "{{ ansible_hostname }}"
    group: "{{ ansible_hostname }}"
    mode: '0644'

- name: Add source command to .bashrc
  lineinfile:
    path: "/home/{{ ansible_hostname }}/.bashrc"
    line: 'source /home/{{ ansible_hostname }}/tpcs-iac/.env'
    insertafter: EOF
    owner: "{{ ansible_hostname }}"
    group: "{{ ansible_hostname }}"
 
- name: Replace vm00 with {{ ansible_hostname }} in aws_ec2.yml
  replace:
    path: /home/{{ ansible_hostname }}/tpcs-iac/vikunja/ansible/aws_ec2.yml
    regexp: 'vm00'
    replace: "{{ ansible_hostname }}"

- name: Replace region in aws_ec2.yml
  replace:
    path: /home/{{ ansible_hostname }}/tpcs-iac/vikunja/ansible/aws_ec2.yml
    regexp: 'eu-west-3'
    replace: "{{ student_tp_vars[tp_name].aws.region_for_apikey }}"

- name: Replace AMI ID in variables.tf
  replace:
    path: /home/{{ ansible_hostname }}/tpcs-iac/vikunja/terraform/variables.tf
    regexp: 'ami-0ec59e7bad062131f'
    replace: "{{ student_tp_vars[tp_name].aws.ami_id }}"

- name: Remove .git directory
  file:
    path: /home/{{ ansible_hostname }}/tpcs-iac/.git
    state: absent

- name: Replace AMI ID in all terraform files
  replace:
    path: /home/{{ ansible_hostname }}/tpcs-iac/terraform/{{ item }}
    regexp: '<AMI-ID-for-your-region>'
    replace: "{{ student_tp_vars[tp_name].aws.ami_id }}"
  with_fileglob:
    - /home/{{ ansible_hostname }}/tpcs-iac/terraform/*

- name: Setup SSH key for TF and Ansible environment
  openssh_keypair:
    path: /home/{{ ansible_hostname }}/tpcs-iac/vikunja/terraform/tp-iac
    owner: "{{ ansible_hostname }}"
    group: "{{ ansible_hostname }}"

- name: Download Terraform
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/terraform/1.6.1/terraform_1.6.1_linux_amd64.zip"
    dest: /tmp/terraform.zip
    mode: '0644'
  register: terraform_download

- name: Create Terraform installation directory
  ansible.builtin.file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Extract Terraform binary
  ansible.builtin.unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
    owner: root
    group: root

- name: Clean up Terraform archive
  ansible.builtin.file:
    path: /tmp/terraform.zip
    state: absent
  when: terraform_download.changed

- name: Verify Terraform installation
  become_user: "{{ ansible_hostname }}"
  ansible.builtin.command: terraform --version
  changed_when: false

- name: Add Ansible PPA repository
  ansible.builtin.apt_repository:
    repo: ppa:ansible/ansible
    state: present

- name: Update apt package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install Ansible
  ansible.builtin.apt:
    name: ansible
    state: present
    update_cache: yes
  loop: 
    - ansible
    - python3-pip
    - python3.10-venv

- name: Verify Ansible installation
  become_user: "{{ ansible_hostname }}"
  ansible.builtin.command: ansible --version
  changed_when: false

