{
 "title": "AWS metrics (usage during TP IaC",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Running instances (except students)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count (aws_instance{state!=\"terminated\",region!=\"eu-west-3\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPC (exept eu-west3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count(aws_vpc{region!=\"eu-west-3\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VM list (running and not guacamole)",
   "type": "table",
   "gridPos": { "h": 9, "w": 21, "x": 1, "y": 8 },
   "targets": [
    {
     "expr": "aws_instance{region!=\"eu-west-3\",state=\"running\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "instances flavor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count (aws_instance{state!=\"terminated\",region!=\"eu-west-3\"}) by (flavor,region)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internet Gateway (Except eu-west3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "count(aws_internet_gateway{region!=\"eu-west-3\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EIP (Except eu-west3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "count(aws_eip{region!=\"eu-west-3\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security Groups (Except eu-west3)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "count(aws_security_group{region!=\"eu-west-3\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}