version: "3.6"
services:
  biblioapi:
    image: "geekbot/biblioapi:latest"
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    ports:
      - "3000:3000"
    stop_grace_period: 1s
    environment:
      - MONGOHOSTNAME=bibliomongo
    networks:
      - biblionet
    depends_on:
      - bibiomongo

  bibliomongo:
    image: "geekbot/bibliomongo:latest"
    deploy:
      restart_policy:
        condition: any
      replicas: 1
      placement:
        constraints:
          - node.hostname == dockmain
    volumes:
    - type: volume
      source: conf.volume
      target: /data/configdb
    - type: volume
      source: data.volume
      target: /data/db
    stop_grace_period: 1s
    networks:
      - biblionet

networks:
  biblionet:
    driver: overlay

volumes:
  conf.volume:
  data.volume:
