
- name: Build list of git repositories for TP
  ansible.builtin.set_fact:
    student_tp_git_repos: >-
      {{
        student_tp_vars[tp_name].git_repos
          | default((student_tp_vars[tp_name].git is defined) | ternary([student_tp_vars[tp_name].git], []), true)
      }}

- name: If forced (not default), remove existing git directories # Not really idempotent but git clone fails if the directory is not empty
  ansible.builtin.file:
    path: "{{ item.local_dir }}"
    state: absent
  loop: "{{ student_tp_git_repos }}"
  when: student_delete_git_dir | bool

- name: Check if git directories already exist
  ansible.builtin.stat:
    path: "{{ item.local_dir }}"
  loop: "{{ student_tp_git_repos }}"
  register: rep_stats

- name: Git clone TP remote repositories
  become_user: "{{ ansible_hostname }}"
  ansible.builtin.git:
    dest: "{{ item.item.local_dir }}"
    repo: "{{ item.item.remote_repo }}"
    version: "{{ item.item.branch }}"
  loop: "{{ rep_stats.results }}"
  when: not (item.stat.exists and item.stat.isdir)

- name: Remove .git directories to break dependency with remote repositories
  ansible.builtin.file:
    path: "{{ item.local_dir }}/.git"
    state: absent
  loop: "{{ student_tp_git_repos }}"
