- name: MICROK8S ADDONS - get current addons state
  command:
    cmd: "microk8s.status --format yaml"
  changed_when: no
  register: microk8s_status
  check_mode: no

- name: MICROK8S ADDONS - set current state fact
  set_fact:
    microk8s_status: "{{ microk8s_status.stdout | from_yaml }}"

- name: MICROK8S ADDONS - enable addons
  loop: "{{ microk8s_status.addons }}"
  loop_control:
    label: "{{ item.name }}"
  command:
    cmd: "microk8s.enable {{ item.name }}"
  when:
    - item.status == 'disabled'
    - item.name in student_tp_vars[tp_name].microk8s_addons