
- name: Remove existing tpcs-iac directory if present # Not really idempotent but git clone fails if the directory is not empty
  # TODO : may be not a good idea if students are working in this directory. 
  # May be better to skip git clone if directory already exists and an optional variable to force the deletion+git clone if necessary
  ansible.builtin.file:
    path: /home/{{ ansible_hostname }}/tpcs-iac
    state: absent

- name: git clone tpiac
  become_user: "{{ ansible_hostname }}"
  ansible.builtin.git:
    dest: /home/{{ ansible_hostname }}/tpcs-iac
    repo: https://github.com/seb54000/tp-cs-containers-student.git

- name: Remove .git directory
  file:
    path: /home/{{ ansible_hostname }}/tpcs-iac/.git
    state: absent

- name: Wait for microk8s to be ready
  command: "microk8s.status --wait-ready"
  changed_when: false
  register: mk8sstatusout
  failed_when:
      - "'This MicroK8s deployment is acting as a node in a cluster.' not in mk8sstatusout.stdout_lines"
      - mk8sstatusout.rc > 0

- name: Add group microk8s to vm user
  ansible.builtin.user:
    name: vm{{ student_count_number_2digits }}
    groups: microk8s
    append: yes
  
- name: Install microk8s addons
  include_tasks: microk8s_addons.yml
