#SPDX-License-Identifier: MIT-0
---

- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ access_docs_apt_packages }}"

- name: Install snap packages
  community.general.snap:
    name: "{{ item.package }}"
    state: present
    classic: "{{ item.classic }}" 
  loop: "{{ access_docs_snap_packages }}"

- name: Create parent directory for custom files
  become_user: "{{ item.owner }}"
  ansible.builtin.file:
    path: "{{ item.dest_path | dirname }}"
    state: directory
    owner: "{{ access_docs_user }}"
    group: "{{ access_docs_user }}"
    mode: '0755'
  loop: "{{ access_docs_custom_files + access_docs_template_files }}"
  when: item.dest_path is defined

- name: Copy static custom files
  become_user: "{{ item.owner }}"
  ansible.builtin.copy:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: '0644'
  loop: "{{ access_docs_custom_files }}"
  when: item.src_path is defined and item.dest_path is defined

- name: Create parent directory for template files
  become_user: "{{ item.owner }}"
  ansible.builtin.file:
    path: "{{ item.dest_path | dirname }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: '0755'
  loop: "{{ access_docs_template_files }}"
  when: item.dest_path is defined

- name: Template and Copy template files
  become_user: "{{ item.owner }}"
  ansible.builtin.template:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: '0644'
  loop: "{{ access_docs_template_files }}"
  when: item.src_path is defined and item.dest_path is defined

- name: Create cron job for vms.php script
  cron:
    name: "Update vms.html summary"
    minute: "*/5"
    user: root
    job: "php {{ access_docs_init_vms_php_file_dir }} > /var/tmp/vms.html && mv /var/tmp/vms.html /var/www/html/vms.html"

- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Run guacamole docker-compose and configure it with terraform
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - guacamole_docker_compose.yml
    - guacamole_configure_with_terraform.yml

- name: Run monitoring docker-compose
  command: docker-compose -f monitoring_docker_compose.yml up -d
  args:
    chdir: "{{ access_docs_monitoring_dir }}"
  become_user: "{{ access_docs_user }}"
  register: docker_compose_monitoring
  changed_when: docker_compose_monitoring.rc == 0
 # TODO SEB UNCOMMENT ? when: tp_name == "tpmon"

- name: Run Bash scripts # TODO : replace scripts with ansible module
  ansible.builtin.command: bash {{ item.dest_path }}
  loop: "{{ access_docs_template_files }}"
  when: item.dest_path is defined and item.dest_path.endswith('.sh')

- name: Gdrive - template and run python script to copy files from gdrive
  ansible.builtin.include_tasks:
    file: copy_from_gdrive.yml
  when: copy_from_gdrive | bool