- name: Ensure cloud-init is done
  command: cloud-init status
  register: cloud_init_result
  until: "'status: done' in cloud_init_result.stdout"
  retries: 30
  delay: 10
  changed_when: false

- name: Install common apt packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ common_apt_packages }}"

- name: Install common snap packages
  community.general.snap:
    name: "{{ item.package }}"
    state: present
    classic: "{{ item.classic }}"    # Optionnel : utilisez 'classic' si le package nécessite un confinement classique
  loop: "{{ common_snap_packages }}"

- name: Copy common static custom files
  ansible.builtin.copy:
    src: "{{ item.src_path }}"
    dest: "{{ item.dest_path }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ common_custom_files }}"
  when: item.src_path is defined and item.dest_path is defined

- name: Install node exporter (to be able to monitor all vms)
  ansible.builtin.include_tasks:
    file: "node_exporter.yml"

- name: Common Bash scripts # TODO : replace scripts with ansible module
  ansible.builtin.command: bash {{ item.dest_path }}
  become_user: root
  loop: "{{ common_custom_files }}"
  when: item.src_path is defined and item.src_path.endswith('.sh')

- name: Schedule daily shutdown at 8pm
  ansible.builtin.cron:
    name: "Daily shutdown at 8pm"
    minute: "0"
    hour: "20"
    job: "sudo shutdown -h now"

# - name: Template and Copy common template files
#   ansible.builtin.template:
#     src: "{{ item.src_path }}"
#     dest: "{{ item.dest_path }}"
#     owner: root
#     group: root
#     mode: '0644'
#   loop: "{{ common_template_files }}"
#   when: item.src_path is defined and item.dest_path is defined

