# demo.aws_ec2.yml
plugin: amazon.aws.aws_ec2

# This sets the region. If empty (the default) default this will include all regions, except possibly
# restricted ones like us-gov-west-1 and cn-north-1.
regions:
- eu-west-3

# https://docs.ansible.com/ansible/latest/collections/amazon/aws/docsite/aws_ec2_guide.html
hostnames:
  - name: 'tag:Name'

keyed_groups:
# - prefix: tag
#   key: tags
- key: tags.roles
  separator: ';'

filters:
  instance-state-name : running