#SPDX-License-Identifier: MIT-0
---
# common (for tp_name) vars file for vms student


# Set to true in extra vars when you want to delete/recreate git directory (ansible-playbook post_install.yml -e student_delete_git_dir=true)
# WARNING : DATA created by student in this directory will be lost
student_delete_git_dir: false 

student_count_number_2digits: "{{ ansible_hostname[-2:] }}"

student_common_apt_packages: 
  - xrdp
  - xfce4

student_common_snap_packages : 
  - package: postman
    classic: false
  - package: insomnia
    classic: false
  - package: helm
    classic: true
  - package: chromium
    classic: false
  - package: code
    classic: true

student_common_custom_files:
  - src_path: common/autorefresh.json
    dest_path: "/var/snap/chromium/current/policies/managed/autorefresh.json"
    owner: root
  - src_path: common/mateterminal.desktop
    dest_path: /home/{{ ansible_hostname }}/.config/autostart/mateterminal.desktop
    owner: root
  - src_path: common/chromium.desktop
    dest_path: /home/{{ ansible_hostname }}/.config/autostart/mateterminal.desktop
    owner: root

student_common_template_files:
  - src_path: common/vscode.desktop.j2
    dest_path: /home/{{ ansible_hostname }}/.config/autostart/vscode.desktop
    owner: root

student_tp_vars:
  tpiac:
    snap_packages: []
    template_files:
      - src_path: tpiac/config.j2
        dest_path: /home/{{ ansible_hostname }}/.aws/config
        owner: "{{ ansible_hostname }}"
      - src_path: tpiac/credentials.j2
        dest_path: /home/{{ ansible_hostname }}/.aws/credentials
        owner: "{{ ansible_hostname }}"
    vscode_extensions:
      - redhat.vscode-yaml
      - redhat.ansible
      - hashicorp.terraform
      - pomdtr.excalidraw-editor
    git:
      local_dir: /home/{{ ansible_hostname }}/tpcs-iac
      remote_repo: https://github.com/seb54000/tpcs-iac.git
      branch: main
    aws:
      region_for_apikey: "{{ tf_vars.tpiac_users.value[ student_count_number_2digits | int ].tpiac_region_list_for_apikey | default()}}"
      access_key: "{{ tf_vars.tpiac_users.value[ student_count_number_2digits | int ].user_apikey | default() }}"
      secret_key: "{{ tf_vars.tpiac_users.value[ student_count_number_2digits | int ].user_apikey_secret | default() }}"
      ami_id: "{{ student_tpiac_ami_for_template_with_regions_list[(student_count_number_2digits | int) % (student_tpiac_ami_for_template_with_regions_list | length)] | default() }}"
  tpkube:
    snap_packages:
      - package: microk8s
        classic: true
      - package: kubectl
        classic: true
      - package: k9s
        classic: false
    template_files:
      - src_path: tpkube/install_tools_for_tpkube.sh.j2
        dest_path: /root/install_tools_for_tpkube.sh
        owner: root
    vscode_extensions:
      - ms-kubernetes-tools.vscode-kubernetes-tools
      - ms-azuretools.vscode-docker
      - pomdtr.excalidraw-editor
    git:
      local_dir: /home/{{ ansible_hostname }}/tpcs-containers
      remote_repo: https://github.com/seb54000/tp-cs-containers-student.git
      branch: main
    microk8s_addons:
      - dns
      - ingress
      - registry
      - hostpath-storage



student_tpiac_ami_for_template_with_regions_list: # Cannot be part of student_tp_vars variable
  # List done with https://cloud-images.ubuntu.com/locator/ec2/ Noble 24.04 + amd64
  - ami-0c4059cd09929aebe #"eu-central-1"
  - ami-0b0087db031e71474", #"eu-west-1"
  - ami-0d3b447228dab952e", #"eu-west-2"
  - ami-061bdb40c12e7d8f1", #"eu-south-1"
  # "eu-west-3", //We keep Paris for guacamole VMs
  - ami-0a60eeae18abc601", #"eu-south-2"
  - ami-0dc1ddd4917dcf47a", #"eu-north-1"
  - ami-08946bcde99d2248b", #"eu-central-2"

